### ISSUE TITLE
Patroni exception on replica re-init

### ISSUE THREAD

**Issue by bearpaws** [timescale/timescaledb-docker-ha#387]
With the `timescale/timescaledb-ha:pg14.7-ts2.10.3` image running in Kubernetes, the following error occurs when doing a manual re-init of a replica:

```
2023-05-09 18:26:46,558 INFO: Removing data directory: /var/lib/postgresql/data
2023-05-09 18:26:46,558 INFO: Removing WAL directory: /var/lib/postgresql/wal/pg_wal
2023-05-09 18:26:52,452 INFO: Lock owner: timescale-0; I am timescale-2
2023-05-09 18:26:52,520 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1710, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1679, in _run_cycle
    if self.state_handler.is_leader():
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 408, in is_leader
    return bool(self._cluster_info_state_get('timeline'))
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 369, in _cluster_info_state_get
    result = self._is_leader_retry(self._query, self.cluster_info_query).fetchone()
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 305, in _query
    raise e
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 294, in _query
    cursor.execute(sql, params or None)
psycopg2.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

To reproduce:
- Install a timescale StatefulSet with a primary and two replicas.
- After all pods are up and replication is steady, re-init one of the replicas:
  ```
  $ patronictl -c config.yaml reinit timescale-cluster
  Which member do you want to reinitialize [timescale-0, timescale-1, timescale-2]? []: timescale-2
  Are you sure you want to reinitialize members timescale-2? [y/N]: y
  Success: reinitialize for member timescale-2
  ```

Then the above python error appears in the replica's log, followed by:
```
2023-05-09 18:27:02,673 INFO: establishing a new patroni connection to the postgres cluster
2023-05-09 18:27:02,674 WARNING: Retry got exception: 'connection problems'
/var/run/postgresql:5432 - no response
2023-05-09 18:27:02,678 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-05-09 18:27:02,678 INFO: reinitialize in progress
```

This repeats forever.  Attempting to re-init again results in the same outcome.

The issue does not occur with `timescale/timescaledb-ha:pg14.7-ts2.10.1-p1`.  It seems to have been introduced in
`timescale/timescaledb-ha:pg14.7-ts2.10.2` where there was a patroni version upgrade:
```
$ patroni --version
patroni 2.1.7
```

But oddly the `/usr/bin/patroni` script mentions version 3.0.1:
```
__requires__ = 'patroni==3.0.1'
```

Does the patroni bundled in the image come from your fork (https://github.com/timescale/patroni)?  Does this version mismatch indicate a problem and possibly relate to the exception?  As a side question, what is the reason for using the fork instead of the official patroni?

**Comment by graveland** [comment]
Things have changed a fair bit since this issue was created. We're not using a fork anymore at the least, so hopefully you aren't still having troubles. Create a new issue if there's still any problems trying this!
